site_name: Tutorial de TwinCAT 3
site_url: https://famoreno.github.io/tc3_tutorial/

theme:
  name: material
  language: es
  #logo: images/_resource/AutoISATeam_logo.png
  #favicon: images/_resource/AutoISATeam_logo.png
  logo: images/_resource/logo_auto_isa_team.png
  favicon: images/_resource/logo_auto_isa_team.png

  palette:
    - scheme: default
      primary: red #blue grey
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Modo oscuro
    - scheme: slate
      primary: red #blue grey
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Modo claro

  font:
    text: Roboto
    code: Roboto Mono

  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Inicio: index.md
  - Beckhoff y TwinCAT 3: contenidos/00_presentacion.md
  - Conceptos Generales: contenidos/01_conceptos.md
  - Ejemplo - Demo: contenidos/02_tc3_demo.md
  - Ejemplo - Carro BÃ¡sico: contenidos/03_tc3_carro_basico.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.snippets:
      check_paths: true
      base_path: !relative $docs_dir
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/famoreno/tc3_tutorial

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/ui-course.js
